# Operações com Matrizes, Determinantes, Autovalores e Autovetores em Ciência de Dados

!pip install -q -U watermark

In [2]:
import numpy as np

In [3]:
%reload_ext watermark
%watermark -a "LF Analytics"

Author: LF Analytics



#### Por que NumPy é mais veloz nas operações matemáticas?

Python é uma excelente linguagem de programação, mas ela pode ser lenta quando usada na sua forma básica. No entanto, ela permite que você acesse bibliotecas que executem código mais rápido em linguagens como C.

NumPy é uma dessas bibliotecas e fornece alternativas rápidas para operações matemáticas em Python e foi projetado para funcionar de forma eficiente com grupos de números - como matrizes.

Numpy é uma excelete biblioteca, sendo a base de quase todos os frameworks de aprendizarem de máquina em Python

O NumPy oferece mais velocidade nas operações em comparação com Python "puro" por várias razões:

**Implementação em C:** O NumPy é escrito principalmente em C, uma linguagem compilada que é muito mais rápida que python, uma linguagem interpretada. Isso significa que muitas de suas operaçoes são executadas em código de máquina, que é executado diretamente pelo processador, oferecendo um desempenho muito mais rapido.

**Otimizações de Array:** NumPy usa arrays multidimensionais (ndarrays) que são armazenados de maneira contínua na memória. Isso é bem diferente das listas do Python, que são arrays de ponteiros para objetos espalhadps pela memória. A representação contínua permite operações mais eficientes de leitura e escrita de dados.

**Operaçoes Vetorizadas:** NumPy permite operações vetorizadas, que são operações aplicadas diretamente a arrays inteiros ao invés de seus elementos individuais (como seria feito em um loop em Python "puro"). Essas operações são otimizadas e executadas em C, resultando em um desempenho muito mais rápido.

**Menos Overhead de verificação de Tipo:** Em python, cada operação inclui verificações de tipo e outras verificações de segurança, que adicionam overhead de processamento. NumPy, por outro lado, trabalha com tipos de dados homogêneos, reduzindo significativamente esse overhead.

**Uso de Bibliotecas de Matemáticas Otinizada:** NumPy é integrado com bibliotecas de matemática otimizdas com BLAS e LAPACK, que são altemente eficientes para operações matemáticas complexas e álgebra linear.

**Paralelização:** Algumas operações do NumPy são intrinsecamente paralelas, permitindo que elas aproveitem processadores multi-core e operações de hardware otimizadas.

Esses fatores combinados fazem com que o NumPy seja muito mais rápido para operações matemáticas e manipulação de dados em grande escala do que o python "puro", especialmente para arrays grandes e calculos complexos.

## Escalares, Vetores, Matrizes e Tensores

A maneira mais comum de trabalhar com número usando NumPy, é através de objetos ndarray. Eles são semelhantes às listas em Python, mas podem ter qualquer número de dimensoes. Além disso, o ndarray suporta operações matemáticas rápidas.
Como você pode armazenar qualquer número de dimensoes, você pode usar o ndarrays para representar qualquer um dos tipos de dados: Escalares, Vetores, Matrizes ou Tensores.

### Escalares

Escalares com NumPy são mais eficientes do que em python. Em vez dos tipos básicos em python como **int, float, etc.**, o NumPy permite especificar tipos mais específicos, bem como diferentes tamanhos. Então, em vez de usar int em python, você tem acesso a tipos como uint8, int8, uint16, int16 e assim por diante, ao usar o NumPy.

Esses tipos são importantes porque todos os objetos que você cria (vetores, matrizes, tensores) acabam armazenando eslacares. E quando você cria uma matriz NumPy, você pode especificar o tipo (mas cada item naa matriz deve ter o mesmo tipo). Nesse sentido, os arrays NumPy são mais como arrays C do que as listas em python.

Se quiser criar uma matriz NumPy que contenha um escalar, usamos a função array do NumPy:

In [4]:
s = np.array(8)
print(f'type: {type(s)}')
print(s)

type: <class 'numpy.ndarray'>
8


Você ainda pode realizar matemática entre ndarrays, escalares NumPy e escalares Python normais.
Você pode ver o shape da matriz usando o atributo shape, conforme abaixo. Esse comando retorna um () vazio, indicando que este objeto é um escalar:


In [5]:
s.shape

()

Mesmo que os escalares estejam dentro de arrays, você ainda os usa como um escalar normal para operações matemáticas:

In [6]:
x = s - 3
print(f'type: {type(x)}')
print(x)

type: <class 'numpy.int64'>
5


Se você verificar o tipo de x, vai perceber que é nympy.int64, pois você está trabalhando com tipos NumPy e não com tipos Python

Mesmo os tipos escalares suportam a maioria das funções de matriz. Então você pode chamar x.shape e retornaria () porque tem zero dimensões, mesmo que não seja uma matriz. Se você tentar usar o objeto como um escalar python, você obterá um erro.

Para criar um vetor, é necessario passar uma lista Python para função array()

In [7]:
vec = np.array([1, 2, 3])
print(f'type: {type(vec)}')
print(f'shape: {vec.shape}')
print(vec)

type: <class 'numpy.ndarray'>
shape: (3,)
[1 2 3]


Pode utilizar o python sem usar pacote numpy, não é recomendado, pois o pacote numpy é preparado para operações matemáticas, principalmente quando se trata de grandes volumes de dados.
Exemplo abaixo:

In [10]:
vec_pp = [1, 2, 3]
print(f'type: {type(vec_pp)}')
print(vec_pp)

type: <class 'list'>
[1, 2, 3]


### Vetores

Ao vertificar o atributo de shape do vetor, ele retornará um único número represetando o comprimento unidimensional do vetor. No exemplo acima vec.shape (3,), ou seja, tem 3 elementos em uma estrutura unidimensional.

Agora que há um número, pode ver que a forma é uma tupla com os tamanhos de cada uma das dimensões do ndarray. Para os escalares, era apenas uma tupla vazia, mas os vetores têm uma dimensão, então a tupla inclui um número e uma vírgula.

(Python não entende (3) como uma tupla com um item, por isso requer a vírgula. Documentação oficial do python sobre tuplas:
https://docs.python.org/3/tutorial/datastructures.htm#tuples-and-sequences)

Pode acessar um elemento dentro do vetorusando índices, como este abaixo (lembrando que a indexação do python sempre começa por 0 e o índice 1 representa o segundo elemento do vetor).

In [14]:
vec2 = np.array([1, 2, 3, 4])
print(f'shape: {vec2.shape}')
print(f'vec2[2]: {vec2[2]}')  # Acessando o terceiro elemento do vetor

shape: (4,)
vec2[2]: 3


NumPy também suporta técnicas avançadas de indexação. Por exemplo, para acessar os itens do segundo elemento em diante, podemos usar:

In [15]:
vec2[1:]

array([2, 3, 4])

NumPy slicing é bastante poderoso, permitindo acessar qualquer combinação de itens em um ndarray. Documentação oficial sobre indexação e slicing de arrays:
https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

### Matrizes

Pode criar matrizes usando a função de array() NumPy, da mesma forma que é com vetores. No entanto, ao invés de passar apenas uma lista, é necessário fornecer uma lista de listas, onde cada lista representa uma linha. Então para criar uma matriz 3x3 contendo os números de um a nove, podemos fazer o seguinte:


In [16]:
m = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
print(f'type: {type(m)}')
print(f'shape: {m.shape}')
print(m)

type: <class 'numpy.ndarray'>
shape: (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Verificando o atributo shape, retorna a tupla (3, 3) indicando que a matriz tem duas dimensões, cada dimensão com comprimento de 3 elementos.

Podemos acessar elementos de matrizes como vetores, mas usando valores de índice adicionais. Então, para encontrar o número 6 na matriz acima, podemos utilizar a seguinte função:


In [17]:
m[1][2]

np.int64(6)

### Tensores