# Regras Básicas da Álgebra, Operações com Vetores e Algorítmo de Machine Learning

## Regras Básicas de Álgebra

##### | Propriedades da Igualdade

In [1]:
# Reflexiva
# Qualquer número ou expressão é igual a si mesmo
a = 5
print(a == a)  # True

True


In [2]:
# Simétrica
# Se A é igual a B, então B é igual a A
a = 5
b = 5
print(a == b)  # True
print(b == a)  # True

True
True


In [3]:
# Transitiva
# Se A é igual a B e B é igual a C, então A é igual a C
a = 5
b = 5
c = 5
print(a == b and b == c)  # True
print(a == c)  # True

True
True


##### | Propriedades das Operações

In [12]:
# Comutativa (adição e multiplicação)
# A ordem dos números não altera o resultado
a = 3
b = 4
print(a + b == b + a)  # True
print(a * b == b * a)  # True

True
True


In [ ]:
# Associativa (adição e multiplicação)
# A forma como os números são agrupados não altera a soma ou o produto
a = 3
b = 4
c = 5 
print((a + b) + c == a + (b + c))  # True
print((a * b) * c == a * (b * c))  # True

True
True


In [2]:
# Distributiva (multiplicação sobre adição)
# A multiplicação distribui sobre a adição
a = 3
b = 4
c = 5 
print(a * (b + c) == (a * b) + (a * c))  # True

True


##### | Elementos Neutros e Inversos

In [ ]:
# Elemento Neutro da Adição e Multiplicação
# O elemento neutro da adição é 0 e da multiplicação é 1
a = 5
print(a + 0 == a)  # True
print(a * 1 == a)  # True

True
True


In [6]:
# Inverso do Aditivo e Multiplicativo
# O inverso aditivo de A é -A e o inverso multiplicativo é 1/A (desde que A != 0)
a = 5
print(a + (-a) == 0)  # True
print(a * (1/a) == 1)  # True, desde que a != 0 

True
True


##### | Regras de Exponenciação

In [7]:
#Produto de mesma base
# A multiplicação de números com a mesma base é igual à base elevada à soma dos expoentes
print(2**3 * 2**4 == 2**(3 + 4))  # True

True


In [8]:
# Divisão de mesma base
# A divisão de números com a mesma base é igual à base elevada à diferença dos expoentes
print(2**5 / 2**3 == 2**(5 - 3))  # True

True


In [9]:
# Potência de potência
# A potência de uma potência é igual à base elevada ao produto dos expoentes
print((2**3)**2 == 2**(3 * 2))  # True

True


In [10]:
# Potência de produto
# A potência de um produto é igual ao produto das potências
print((2 * 3)**2 == (2**2) * (3**2))  # True

True


In [11]:
# Expoente zero
# Qualquer número elevado a zero é igual a 1 (exceto zero elevado a zero, que é indeterminado)
print(5**0 == 1)  # True

True


##### | Regras de Radicais

In [35]:
# Raiz de um Produto ** Atenção ao calculo de ponto flutuante 
# A raiz de um produto é igual ao produto das raízes
import math
print(math.sqrt(2 * 8) == math.sqrt(2) * math.sqrt(8))  # True

# Vamos adicionar tolerância ao calculo de ponto flutuante
a = math.sqrt(2 * 8)
b = math.sqrt(2) * math.sqrt(8)
tolerance = 1e-10

print(a)
print(b)
print(f"Round {round(a, 0)} == {round(b, 0)}: {round(a, 0) == round(b, 0)}") # True, arredondando para o inteiro mais próximo
print(f"Round sqrt: {round(math.sqrt(2 * 8)) == round(math.sqrt(2) * math.sqrt(8))}")  # True
print(abs(a - b) < tolerance)  # True, considerando a tolerância

False
4.0
4.000000000000001
Round 4.0 == 4.0: True
Round sqrt: True
True


In [15]:
# Raiz de um Quociente
# A raiz de um quociente é igual ao quociente das raízes
print(math.sqrt(16 / 4) == math.sqrt(16) / math.sqrt(4))  # True

True


##### | Regras de Polinômios (Adição e Subtração de Termos Semelhantes)

In [36]:
# Regras de polinômios (Adição e Subtração de termos semelhantes)
# A adição e subtração de polinômios envolve combinar termos semelhantes

# Polinômios: 2x^2 + 3x + 4 e 3x^2 - 2x + 1
# Adição: (2x^2 + 3x^2) + (3x - 2x) + (4 + 1)
# Subtração: (2x^2 - 3x^2) + (3x + 2x) + (4 - 1)

# Variável
x = 2

# Calcula a adiçõ dos polinômios
print((2*x**2 + 3*x**2) + (3*x - 2*x) + (4 + 1))  # 7*x**2 + x + 5

27


##### | Regras de Frações

In [37]:
# Multiplicação
# Frações
print((1/2) * (3/4)) # 0.375

#Divisão
# Frações
print((1/2) / (3/4)) # 0.6666666666666666

#Soma e Subtração com Denominador comum
# Fraçoes
print((1/4) + (3/4))  # 1.0



0.375
0.6666666666666666
1.0


## Operações com Vetores

### Operações com Vetores - Adição e Subtração

In [39]:
# Definindo dois vetores como listas
vetor_a = [3, 4, 5]
vetor_b = [1, 2, 3]

In [ ]:
# Função para adição de vetores
def adicionar_vetores(a, b):
    return [a[i] + b[i] for i in range(len(a))] # list comprehension para somar os elementos correspondentes dos vetores

# Função para subtração de vetores
def subtrair_vetores(a, b):
    return [a[i] - b[i] for i in range(len(a))]

In [43]:
# Realizando as operações
vetor_soma = adicionar_vetores(vetor_a, vetor_b)
vetor_diferenca = subtrair_vetores(vetor_a, vetor_b)

# Exibindo os resultados
print("Vetor A:", vetor_a)  # Vetor A: [3, 4, 5]
print("Vetor B:", vetor_b)  # Vetor B: [1, 2, 3]
print("Soma dos vetores:", vetor_soma)  # Soma dos vetores: [4, 6, 8]
print("Diferença dos vetores:", vetor_diferenca)  # Diferença dos vetores: [2, 2, 2]

Vetor A: [3, 4, 5]
Vetor B: [1, 2, 3]
Soma dos vetores: [4, 6, 8]
Diferença dos vetores: [2, 2, 2]


### Operações com Vetores - Cross Product (Produto Vetorial)
- O produto vetorial entre dois vetores resulta em um terceiro vetor que perpendicular aos dois vertores originais

In [64]:
# Função para calcular o produto vetorial entre dois vetores
# x = (ay*bz) - (az*by)
# y = (az*bx) - (ax*bz)
# z = (ax*by) - (ay*bx)

def produto_vetorial(v1, v2):
    x = v1[1] * v2[2] - v1[2] * v2[1]
    y = v1[2] * v2[0] - v1[0] * v2[2]
    z = v1[0] * v2[1] - v1[1] * v2[0]
    return [x, y, z]

# Criar vetores de exemplo
vetor_a = [2, -3, 1]
vetor_b = [5, 7, 6]

vetor_x = (vetor_a[1] * vetor_b[2]) - (vetor_a[2] * vetor_b[1])
print(f"Vetor X: (v1[{vetor_a[1]}] * v2[{vetor_b[2]}]) - (v1[{vetor_a[2]}] * v2[{vetor_b[1]}]) =", vetor_x)  # Vetor X: -25

vetor_y = (vetor_a[2] * vetor_b[0]) - (vetor_a[0] * vetor_b[2])
print(f"Vetor Y: (v1[{vetor_a[2]}] * v2[{vetor_b[0]}]) - (v1[{vetor_a[0]}] * v2[{vetor_b[2]}]) =", vetor_y)  # Vetor Y: -7

vetor_z = (vetor_a[0] * vetor_b[1]) - (vetor_a[1] * vetor_b[0])
print(f"Vetor Z: (v1[{vetor_a[0]}] * v2[{vetor_b[1]}]) - (v1[{vetor_a[1]}] * v2[{vetor_b[0]}]) =", vetor_z)  # Vetor Z: 29

# Calculando o produto vetorial 
resultado = produto_vetorial(vetor_a, vetor_b)
print("Produto vetorial:", resultado)  # Produto vetorial: [-25, -7, 29]

Vetor X: (v1[-3] * v2[6]) - (v1[1] * v2[7]) = -25
Vetor Y: (v1[1] * v2[5]) - (v1[2] * v2[6]) = -7
Vetor Z: (v1[2] * v2[7]) - (v1[-3] * v2[5]) = 29
Produto vetorial: [-25, -7, 29]


### Operações com Vetores - Dot Product (Produto Escalar)
- O produto escalar de dois vetores é uma operação que resulta em um escalar (um número). Matemáticamente, é a soma dos produtos dos componentes correspondetes dos vetores.

In [66]:
# Função para calcular o produto escalar
# # O produto escalar é a soma dos produtos dos componentes correspondentes dos vetores
# a * b = |a| * |b| * cos(θ) => Onde |a| e |b| são os módulos dos vetores e θ é o ângulo entre eles.
# O produto escalar é uma operação que resulta em um número (escalar) e é definido como a soma dos produtos dos componentes correspondentes de dois vetores.
# Em termos matemáticos, para dois vetores v1 = [v1x, v1y, v1z] e v2 = [v2x, v2y, v2z], o produto escalar é dado por:
# a * b = (ax * bx) + (ay * by)

def produto_escalar(v1, v2):
    return sum(a * b for a, b in zip(v1, v2)) # zip combina os elementos dos dois vetores em pares

# Criar vetores de exemplo
vetor_a = [2, -3, 1]
vetor_b = [5, 7, 6]

va_x_vb = (vetor_a[0] * vetor_b[0]) + (vetor_a[1] * vetor_b[1] + (vetor_a[2] * vetor_b[2]))
print(f"Produto escalar: (v1[{vetor_a[0]}] * v2[{vetor_b[0]}]) + (v1[{vetor_a[1]}] * v2[{vetor_b[1]}]) + (v1[{vetor_a[2]}] * v2[{vetor_b[2]}]) =", va_x_vb)  # Produto escalar: 5


# Calculando o produto escalar
resultado_escalar = produto_escalar(vetor_a, vetor_b)
print("Produto escalar:", resultado_escalar)  # Produto escalar: -5

Produto escalar: (v1[2] * v2[5]) + (v1[-3] * v2[7]) + (v1[1] * v2[6]) = -5
Produto escalar: -5


## Algorítimo de Machine Learning

### Machine Learning apenas com Operações Matemáticas (Sem uso de Frameworks)
- Vamos criar um modelo capaz de prever o preço de um ativo financeiro com taxa nominal de juros

In [68]:
# Gerando dados sintéticos para análise
import numpy as np

np.random.seed(0) # Definindo a semente para reprodutibilidade
X = np.random.randint(1, 10, size = (100, 1)) # 100 instâncias, valores entre 1 e 10
y = 50000 + 30000 * X + np.random.randn(100, 1) * 15000 # Relação linear: preço base + preço por ativo + ruido

In [77]:
# Visualizando os dados
X[1:5]  # Exibindo as primeiras 5 instâncias de X

array([[1],
       [4],
       [4],
       [8]], dtype=int32)

In [78]:
# Visualizando os dados
y[1:5]  # Exibindo as primeiras 5 instâncias de y

array([[ 85385.04146705],
       [186141.81556278],
       [172882.11251578],
       [302793.88936252]])

In [79]:
# Adicionar coluna de uns para o termo de interceptação
X_b = np.c_[np.ones((100, 1)), X] # Adiciona x0 = 1 a cada instância
X_b[1:5]  # Exibindo as primeiras 5 instâncias de X_b

array([[1., 1.],
       [1., 4.],
       [1., 4.],
       [1., 8.]])

##### Função de Custo MSE com Operações Entre Vetores
- Esta função compute_cost é uma implementação da função de custo de erro quadrático médio, que é amplamente usada em regressão linear. O objetivo dessa função é medir quão bem o modelo de regressão (representado pelos parâmetros theta) está desempenhando em relação ao conjunto de dados (X e y). Um custo mais baixo indica que o modelo está fazendo previsões mais precisas.

In [80]:
# Função de custo MSE (Mean Squared Error) com operações entre vetores
def custo_mse(X, y, theta): # theta são os parâmetros do modelo, onde theta[0] é o intercepto e theta[1] é o coeficiente angular, matriz de pesos
    # m é o número de exemplos de treinamento (observações) no conjunto de dados
    m = len(y)
    
    # Calcula a função de custo para regressão linear
    # A função de custo é a média dos erros quadráticos entre as previsões e os valores reais
    # (1/(2*m)) é um fator de escla comum na função de custo do erro quadrático médio
    # np.sum(np.square(X.dot(theta) - y)) é a soma dos quadrados dos erros
    # X.dot(theta) é o produto esalar de X (dados de entrada) e theta (parâmetros do modelo)
    # X.dot(theta) - y é a diferença entre as previsões e os valores reais
    cost = (1 / (2 * m)) * np.sum(np.square(X.dot(theta) - y)) # square calcula o quadrado dos elementos do array resultante da subtração
    
    return cost
    

##### Algoritmo Gradiente Descendente com Operações Entre Vetores

In [84]:
# Gradiente descendente para encontrar os parâmetros ótimos
def gradient_descent(X, y, theta, learning_rate, iterations):
    
    # m é o número de exemplos de treinamento (observações) no conjunto de dados
    m = len(y)
    
    # Inicializa um array para armazenar o histórico do custo em cada iteração
    cost_history = np.zeros(iterations)
    
    # Loop para realizar o número especificado de iterações
    for i in range(iterations):
        
        # Calcula o gradiente da função de custo em relação aos parâmetros theta
        # O gradiente é a média dos produtos dos erros e as características de entrada
        gradients = (1 / m) * X.T.dot(X.dot(theta) - y)  # X.T é a transposta de X, dot é o produto escalar
        
        # Atualiza os parâmetros theta subtraindo o produto da taxa de aprendizado e o gradiente
        # Esta é a regra de descida do gradiente, movendo-se em direção o mínimo da função de custo
        theta -= learning_rate * gradients
        
        # Calcula o custo com o theta atualizado e armazena no histórico de custo
        cost_history[i] = custo_mse(X, y, theta)
        
    # Retorna os parâmetros theta otimizados e o histórico de custo
    return theta, cost_history

##### Treinamento do Modelo

In [81]:
# Parâmetros iniciais

# inicializa os parâmetros randomicamente
theta = np.random.randn(2, 1)  # Dois parâmetros: intercepto e coeficiente angular
learning_rate = 0.01  # Taxa de aprendizado
iterations = 1000  # Número de passadas de treino

In [90]:
#Treinando o modelo
theta_final, cost_history = gradient_descent(X_b, y, theta, learning_rate, iterations)
print(f"Modeo de ML - Parâmetros finais:\n {np.round(theta_final, 2)}")  # Exibindo os parâmetros finais do modelo

Modeo de ML - Parâmetros finais:
 [[49418.96]
 [30250.85]]


##### Deploy e previsão com novos dados

In [88]:
# Novo valor de X
X_new = np.array([[4.5]])

# Novo valor de bias
X_new_b = np.c_[np.ones((1, 1)), X_new]  # Adiciona x0 = 1 para o novo valor de X

#Previsão
y_predict = X_new_b.dot(theta_final)  # Calcula a previsão usando os parâmetros finais do modelo
print(f"Com base na taxa de juros nominal, a previsão do preço do ativo é:\n {np.round(y_predict, 2)}")  # Exibindo a previsão arredondada para duas casas decimais

Com base na taxa de juros nominal, a previsão do preço do ativo é:
 [[185530.04]]


In [91]:
%reload_ext watermark
%watermark -a "LFernandes" -v -m

Author: LFernandes

Python implementation: CPython
Python version       : 3.12.6
IPython version      : 9.2.0

Compiler    : MSC v.1940 64 bit (AMD64)
OS          : Windows
Release     : 11
Machine     : AMD64
Processor   : AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
CPU cores   : 12
Architecture: 64bit



In [92]:
%watermark --iversions

numpy: 2.2.6

